app:
  port: ':4500'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'

es:
  host: '192.168.0.105'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'
  batch_size: 50

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  match_key_format: 'suggestion.%s'